# Generated by Django 3.1.4 on 2022-12-05 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment_T',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assessment_name', models.CharField(max_length=30, null=True)),
                ('marks_obstained', models.FloatField()),
                ('total_marks', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CLO_T',
            fields=[
                ('clo_pk', models.AutoField(primary_key=True, serialize=False)),
                ('clo_no', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Course_T',
            fields=[
                ('course_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('no_of_credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department_T',
            fields=[
                ('dept_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_T',
            fields=[
                ('emp_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30, null=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coqb.department_t')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_T',
            fields=[
                ('plo_pk', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.CharField(max_length=5)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coqb.employee_t')),
            ],
        ),
        migrations.CreateModel(
            name='PLO_T',
            fields=[
                ('plo_pk', models.AutoField(primary_key=True, serialize=False)),
                ('plo_no', models.CharField(max_length=5)),
                ('details', models.CharField(max_length=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coqb.course_t')),
            ],
        ),
        migrations.CreateModel(
            name='School_T',
            fields=[
                ('school_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student_T',
            fields=[
                ('student_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=30, null=True)),
                ('l_name', models.CharField(max_length=30, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('address', models.CharField(max_length=30, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coqb.department_t')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section_T',
            fields=[
                ('section_pk', models.AutoField(primary_key=True, serialize=False)),
                ('section_no', models.IntegerField()),
                ('semester', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coqb.course_t')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coqb.faculty_t')),
            ],
        ),
        migrations.CreateModel(
            name='Registration_T',
            fields=[
                ('registration_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=6)),
                ('year', models.CharField(max_length=4)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coqb.student_t')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBank_T',
            fields=[
                ('qb_pk', models.AutoField(primary_key=True, serialize=False)),
                ('question_no', models.CharField(max_length=5)),
                ('blooms_taxonomy_level', models.CharField(max_length=30)),
                ('marks', models.CharField(max_length=30)),
                ('clo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coqb.clo_t')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coqb.course_t')),
                ('plo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coqb.plo_t')),
            ],
        ),
        migrations.CreateModel(
            name='Program_T',
            fields=[
                ('program_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=30)),
                ('department', models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, to='coqb.department_t')),
            ],
        ),
        migrations.AddField(
            model_name='plo_t',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coqb.program_t'),
        ),
        migrations.CreateModel(
            name='Exam_T',
            fields=[
                ('exam_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=30)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coqb.questionbank_t')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation_T',
            fields=[
                ('evaluation_id', models.AutoField(primary_key=True, serialize=False)),
                ('marks_obtained', models.FloatField()),
                ('assessment', models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, to='coqb.assessment_t')),
            ],
        ),
        migrations.AddField(
            model_name='department_t',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coqb.school_t'),
        ),
        migrations.CreateModel(
            name='Department_Head',
            fields=[
                ('emp_pk', models.AutoField(primary_key=True, serialize=False)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coqb.employee_t')),
            ],
        ),
        migrations.CreateModel(
            name='Dean_T',
            fields=[
                ('emp_pk', models.AutoField(primary_key=True, serialize=False)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coqb.employee_t')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coqb.school_t')),
            ],
        ),
        migrations.CreateModel(
            name='CourseOutline_T',
            fields=[
                ('co_pk', models.AutoField(primary_key=True, serialize=False)),
                ('co_no', models.CharField(max_length=5)),
                ('course_type', models.CharField(max_length=30)),
                ('course_name', models.CharField(max_length=30)),
                ('credit_value', models.CharField(max_length=30)),
                ('course_hour', models.CharField(max_length=30)),
                ('course_description', models.CharField(max_length=30)),
                ('course_obj', models.CharField(max_length=30)),
                ('course_policy', models.CharField(max_length=30)),
                ('academic_dishonesty', models.CharField(max_length=30)),
                ('student_disability', models.CharField(max_length=30)),
                ('non_discrimination', models.CharField(max_length=30)),
                ('course_content', models.CharField(max_length=30)),
                ('clo_matrix', models.CharField(max_length=30)),
                ('mapping_clo_with_plo', models.CharField(max_length=30)),
                ('assesment_evaluation_section', models.CharField(max_length=30)),
                ('grading_chart', models.CharField(max_length=30)),
                ('course_requrement', models.CharField(max_length=30)),
                ('reference', models.CharField(max_length=30)),
                ('clo_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coqb.clo_t')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coqb.course_t')),
                ('plo_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coqb.plo_t')),
            ],
        ),
        migrations.AddField(
            model_name='course_t',
            name='department',
            field=models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, to='coqb.department_t'),
        ),
        migrations.AddField(
            model_name='course_t',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coqb.program_t'),
        ),
        migrations.AddField(
            model_name='clo_t',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coqb.course_t'),
        ),
        migrations.AddField(
            model_name='clo_t',
            name='plo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coqb.plo_t'),
        ),
        migrations.AddField(
            model_name='assessment_t',
            name='co_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coqb.clo_t'),
        ),
        migrations.AddField(
            model_name='assessment_t',
            name='section',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='coqb.section_t'),
        ),
    ]
